import type { PortalTenant } from '../types/portal';

export const TENANTS: PortalTenant[] = [
    {
        id: 'saolucas',
        name: 'Hospital São Lucas',
        shortName: 'São Lucas',
        initials: 'SL',
        tagline: 'Cuidado completo, do começo ao fim.',
        vibe: 'institutional',
        primary: '#1f3fb8',
        primaryHover: '#1a35a0',
        primarySoft: '#e8edfb',
        primarySoft2: '#d6deef',
        logoGradient: ['#2447c0', '#1a3196'],
        heroGradient: ['#1d3aa8', '#142776', '#0e1d5a'],
        phone: '0800 555 1212',
        email: 'contato@saolucas.com.br',
        address: 'Av. Paulista, 1500 — São Paulo',
    },
    {
        id: 'verdevida',
        name: 'Clínica Verde Vida',
        shortName: 'Verde Vida',
        initials: 'VV',
        tagline: 'Saúde integrativa, atenção humana.',
        vibe: 'wellness',
        primary: '#0e7e6b',
        primaryHover: '#0a6b5a',
        primarySoft: '#def0eb',
        primarySoft2: '#bce0d4',
        logoGradient: ['#10967e', '#0a6b5a'],
        heroGradient: ['#0f8a73', '#0a6b5a', '#054a3e'],
        phone: '0800 777 8080',
        email: 'ola@verdevida.com.br',
        address: 'R. das Magnólias, 220 — Curitiba',
    },
    {
        id: 'institutocor',
        name: 'InstitutoCor',
        shortName: 'InstitutoCor',
        initials: 'IC',
        tagline: 'Cardiologia de alta precisão.',
        vibe: 'cardiology',
        primary: '#a8243a',
        primaryHover: '#8e1c30',
        primarySoft: '#fbe3e7',
        primarySoft2: '#f4c6cd',
        logoGradient: ['#bc2c43', '#8e1c30'],
        heroGradient: ['#b32a40', '#88182e', '#5e0e20'],
        phone: '0800 333 4040',
        email: 'atendimento@institutocor.med.br',
        address: 'Av. Brig. Faria Lima, 3500 — São Paulo',
    },
    {
        id: 'maternacare',
        name: 'MaternaCare',
        shortName: 'MaternaCare',
        initials: 'MC',
        tagline: 'Cuidando de você e do seu bebê.',
        vibe: 'maternity',
        primary: '#6a4ec1',
        primaryHover: '#5b41a8',
        primarySoft: '#ebe5fa',
        primarySoft2: '#d8ceee',
        logoGradient: ['#7e5edd', '#5b41a8'],
        heroGradient: ['#7657d3', '#5b41a8', '#3e2a7c'],
        phone: '0800 222 9090',
        email: 'familia@maternacare.com.br',
        address: 'Al. Santos, 800 — São Paulo',
    },
];
