import type { PortalTenant } from '../types/portal';

const CIS_BRAND = {
    primary: '#3a8b5a',
    primaryHover: '#2f7349',
    primarySoft: '#e5f2eb',
    primarySoft2: '#cde5d7',
    logoGradient: ['#3a8b5a', '#2c6b44'] as [string, string],
    heroGradient: ['#3a8b5a', '#2c6b44', '#1e4d31'] as [string, string, string],
};

export const TENANTS: PortalTenant[] = [
    {
        id: 'saolucas',
        name: 'Hospital São Lucas',
        shortName: 'São Lucas',
        initials: 'SL',
        tagline: 'Cuidado completo, do começo ao fim.',
        vibe: 'institutional',
        ...CIS_BRAND,
        phone: '0800 555 1212',
        email: 'contato@saolucas.com.br',
        address: 'Av. Paulista, 1500 — São Paulo',
    },
    {
        id: 'verdevida',
        name: 'Clínica Verde Vida',
        shortName: 'Verde Vida',
        initials: 'VV',
        tagline: 'Saúde integrativa, atenção humana.',
        vibe: 'wellness',
        ...CIS_BRAND,
        phone: '0800 777 8080',
        email: 'ola@verdevida.com.br',
        address: 'R. das Magnólias, 220 — Curitiba',
    },
    {
        id: 'institutocor',
        name: 'InstitutoCor',
        shortName: 'InstitutoCor',
        initials: 'IC',
        tagline: 'Cardiologia de alta precisão.',
        vibe: 'cardiology',
        ...CIS_BRAND,
        phone: '0800 333 4040',
        email: 'atendimento@institutocor.med.br',
        address: 'Av. Brig. Faria Lima, 3500 — São Paulo',
    },
    {
        id: 'maternacare',
        name: 'MaternaCare',
        shortName: 'MaternaCare',
        initials: 'MC',
        tagline: 'Cuidando de você e do seu bebê.',
        vibe: 'maternity',
        ...CIS_BRAND,
        phone: '0800 222 9090',
        email: 'familia@maternacare.com.br',
        address: 'Al. Santos, 800 — São Paulo',
    },
];
